-- Initial Content: the approved Skill list and the six Projects.
-- Run once on an empty database, after the migrations.

insert into public.skill_categories (name_pl, name_en, sort_order) values
  ('Języki', 'Languages', 1),
  ('Frontend', 'Frontend', 2),
  ('UI i stylowanie', 'UI and styling', 3),
  ('Stan i dane', 'State and data', 4),
  ('Backend i bazy danych', 'Backend and databases', 5),
  ('Testy', 'Testing', 6),
  ('Narzędzia i wdrożenia', 'Tools and deployment', 7),
  ('Monitoring i analityka', 'Monitoring and analytics', 8),
  ('AI', 'AI', 9);

insert into public.skills (name, category_id, sort_order)
select skill.name, category.id, skill.sort_order
from (values
  ('TypeScript', 'Języki', 1),
  ('JavaScript', 'Języki', 2),
  ('HTML', 'Języki', 3),
  ('CSS', 'Języki', 4),
  ('React', 'Frontend', 1),
  ('Next.js', 'Frontend', 2),
  ('i18next', 'Frontend', 3),
  ('Tailwind CSS', 'UI i stylowanie', 1),
  ('shadcn/ui', 'UI i stylowanie', 2),
  ('CSS Modules', 'UI i stylowanie', 3),
  ('Recharts', 'UI i stylowanie', 4),
  ('Redux Toolkit', 'Stan i dane', 1),
  ('TanStack Query', 'Stan i dane', 2),
  ('SWR', 'Stan i dane', 3),
  ('React Hook Form', 'Stan i dane', 4),
  ('Zod', 'Stan i dane', 5),
  ('Axios', 'Stan i dane', 6),
  ('Node.js', 'Backend i bazy danych', 1),
  ('Express', 'Backend i bazy danych', 2),
  ('REST API', 'Backend i bazy danych', 3),
  ('Prisma', 'Backend i bazy danych', 4),
  ('PostgreSQL', 'Backend i bazy danych', 5),
  ('MongoDB', 'Backend i bazy danych', 6),
  ('Supabase', 'Backend i bazy danych', 7),
  ('Vitest', 'Testy', 1),
  ('Testing Library', 'Testy', 2),
  ('Playwright', 'Testy', 3),
  ('Git', 'Narzędzia i wdrożenia', 1),
  ('GitHub', 'Narzędzia i wdrożenia', 2),
  ('GitHub Actions', 'Narzędzia i wdrożenia', 3),
  ('Vite', 'Narzędzia i wdrożenia', 4),
  ('Vercel', 'Narzędzia i wdrożenia', 5),
  ('Figma', 'Narzędzia i wdrożenia', 6),
  ('Jira', 'Narzędzia i wdrożenia', 7),
  ('Lokalise', 'Narzędzia i wdrożenia', 8),
  ('Sentry', 'Monitoring i analityka', 1),
  ('Mixpanel', 'Monitoring i analityka', 2),
  ('Google Analytics', 'Monitoring i analityka', 3),
  ('Claude Code', 'AI', 1),
  ('Codex', 'AI', 2),
  ('Mastra', 'AI', 3),
  ('Vercel AI SDK', 'AI', 4),
  ('n8n', 'AI', 5),
  ('MCP', 'AI', 6)
) as skill (name, category, sort_order)
join public.skill_categories as category on category.name_pl = skill.category;

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'eventtracker',
  1,
  true,
  'EventTracker',
  'EventTracker',
  'Landingi',
  'Landingi',
  'Wbudowane w Landingi narzędzie analityczne. Automatycznie zbiera zdarzenia z opublikowanych landing page’y i pokazuje je w dashboardzie — bez konfiguracji po stronie klienta.',
  'An analytics tool built into Landingi. It collects events from published landing pages automatically and shows them in a dashboard, with no setup on the customer’s side.',
  '[{"value":"1,2 mln+","label":"sesji dziennie"},{"value":"< 25 kB","label":"skryptu śledzącego"}]',
  '[{"value":"1.2M+","label":"sessions a day"},{"value":"< 25 kB","label":"tracking script"}]',
  'Klienci Landingi potrzebowali danych o tym, jak odwiedzający zachowują się na ich landing page’ach — żeby lepiej rozumieć swoich klientów i trafniej dobierać treści, a w efekcie zdobywać więcej leadów i więcej sprzedawać. I to bez konfigurowania narzędzi i wklejania kodu. Rozwiązaniem jest analityka wbudowana w platformę, która zbiera zdarzenia automatycznie na każdej opublikowanej stronie.',
  'Landingi customers needed data on how visitors behave on their landing pages, so they could understand their own customers better and choose content more accurately, which in turn means more leads and more sales. And they needed it without configuring tools or pasting code. The answer is analytics built into the platform that collects events automatically on every published page.',
  'Architektura całości po stronie klienckiej oraz implementacja frontendu — dashboard analityczny i skrypt śledzący. Przepływ danych zaprojektowałem sam; poza moim zakresem było wyłącznie ich składowanie na backendzie.',
  'The whole client-side architecture and the frontend implementation: the analytics dashboard and the tracking script. I designed the data flow myself; only storing the data on the backend was outside my scope.',
  '[]',
  '[]',
  '[{"title":"Skrypt, który nie może kosztować klienta wyników","body":"Skrypt trafia na strony klientów, więc każdy kilobajt i każda milisekunda obciążają ich Core Web Vitals. Napisałem go w czystym TypeScripcie, z minimalnymi zależnościami i konfiguracją Vite nastawioną na rozmiar paczki — plik wynikowy waży poniżej 25 kB. Zdarzenia wysyła sendBeacon z throttlingiem po stronie klienta, żeby nie obciążać głównego wątku ani sieci użytkownika."},{"title":"Dashboard przy dużym wolumenie zdarzeń","body":"Paginacja zamiast ładowania pełnych zbiorów, cache i deduplikacja zapytań w SWR oraz optimistic UI przy zmianach konfiguracji, żeby interfejs odpowiadał natychmiast."}]',
  '[{"title":"A script that must not cost customers their scores","body":"The script runs on customers’ pages, so every kilobyte and millisecond weighs on their Core Web Vitals. I wrote it in plain TypeScript with minimal dependencies and a Vite config tuned for bundle size; the output weighs under 25 kB. Events are sent with sendBeacon and throttled on the client so they don’t load the main thread or the visitor’s network."},{"title":"A dashboard for a high volume of events","body":"Pagination instead of loading full data sets, request caching and deduplication with SWR, and optimistic UI for configuration changes so the interface responds instantly."}]',
  '["Zdarzenia zbierane z ponad 1,2 mln sesji dziennie.","Dane z EventTrackera stały się podstawą kilkunastu kolejnych funkcjonalności platformy.","Dostęp do danych jest osobno monetyzowany w abonamencie."]',
  '["Events collected from over 1.2 million sessions a day.","EventTracker data became the basis for more than a dozen further platform features.","Access to the data is monetised separately in the subscription."]',
  '[{"label":"Dashboard","items":["React","TypeScript","SWR","Recharts"]},{"label":"Skrypt śledzący","items":["TypeScript bez frameworka","Vite","własna konfiguracja builda"]},{"label":"CI/CD","items":["GitHub Actions"]}]',
  '[{"label":"Dashboard","items":["React","TypeScript","SWR","Recharts"]},{"label":"Tracking script","items":["framework-free TypeScript","Vite","custom build config"]},{"label":"CI/CD","items":["GitHub Actions"]}]',
  '[{"label":"Strona produktowa","url":"https://landingi.com/pl/produkt/eventtracker/"},{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"Product page","url":"https://landingi.com/product/eventtracker/"},{"label":"Repository","note":"closed source"}]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'solis',
  2,
  true,
  'Solis — agent AI',
  'Solis — AI agent',
  'Landingi',
  'Landingi',
  'Agent AI, który na podstawie danych z EventTrackera sam cyklicznie podsuwa rekomendacje. W czacie odpowiada na pytania o dane i na żywo wskazuje zmiany podnoszące konwersję.',
  'An AI agent that regularly makes recommendations on its own from EventTracker data. In a chat it answers questions about the data and suggests changes that raise conversion, streamed live.',
  '[{"value":"Kilkuset","label":"aktywnych klientów"}]',
  '[{"value":"Hundreds of","label":"active customers"}]',
  'Klienci Landingi mają dostęp do dużej ilości danych o swoich landing page’ach, ale samo posiadanie danych nie mówi im, co poprawić. Solis interpretuje te dane i zamienia je w konkretne rekomendacje.',
  'Landingi customers have plenty of data about their landing pages, but having the data doesn’t tell them what to improve. Solis interprets that data and turns it into concrete recommendations.',
  'Warstwa frontowa produktu oraz agent AI. Endpointy, z których agent korzysta w swoich skillach, powstały po stronie backendu; architekturę całości ustalaliśmy wspólnie w zespole. Agent korzysta między innymi z danych zbieranych przez EventTracker, którego architekturę i frontend budowałem wcześniej.',
  'The product’s frontend and the AI agent. The endpoints the agent calls from its skills were built on the backend, and we agreed on the overall architecture together as a team. Among other sources, the agent uses data collected by EventTracker, whose architecture and frontend I had built earlier.',
  '["Agent AI oparty o Mastrę — pojedynczy agent z zestawem skilli sięgających po dane o stronie i zachowaniu użytkowników.","Dobór modelu pod kątem relacji kosztu do jakości odpowiedzi, zamiast domyślnego sięgania po najdroższy dostępny.","Historia rozmowy w wątkach, utrzymywana po stronie backendu.","Odpowiedzi w markdownie streamowane do interfejsu, żeby użytkownik widział tekst w trakcie generowania, a nie czekał na całość.","Udział w generowaniu insightów w tle: strony klientów są analizowane pod kątem kilku aspektów, razem z danymi behawioralnymi z EventTrackera, a sam insight powstaje w przepływie zbudowanym w n8n."]',
  '["An AI agent built on Mastra: a single agent with a set of skills that fetch data about the page and about visitor behaviour.","Choosing the model for the best balance of cost and answer quality, instead of defaulting to the most expensive one available.","Conversation history kept in threads on the backend.","Markdown answers streamed to the interface, so users see the text as it is generated instead of waiting for the whole response.","Contributing to background insight generation: customers’ pages are analysed from several angles together with behavioural data from EventTracker, and the insight itself is produced in a workflow built in n8n."]',
  '[{"title":"Koszt wywołań modelu","body":"Ograniczany przez skracanie kontekstu przekazywanego do modelu oraz cache, zamiast wysyłania pełnych zestawów danych przy każdym zapytaniu."},{"title":"Niedeterminizm","body":"Odpowiedź modelu nie jest powtarzalna, więc interfejs i przepływ muszą znosić zmienną jakość i formę wyniku."},{"title":"Błędy i timeouty modelu","body":"W zależności od tego, co konkretnie zawiodło, użytkownik dostaje odpowiedni widok błędu z możliwością ponowienia pytania, zamiast pustego ekranu."}]',
  '[{"title":"The cost of model calls","body":"Kept down by trimming the context sent to the model and by caching, instead of sending full data sets with every request."},{"title":"Non-determinism","body":"The model’s answers aren’t repeatable, so the interface and the flow have to cope with output that varies in quality and form."},{"title":"Model errors and timeouts","body":"Depending on what exactly failed, the user gets a matching error view with the option to ask again, instead of a blank screen."}]',
  '["Z funkcjonalności korzysta kilkuset klientów, którzy aktywnie pytają o insighty i dane, żeby poprawiać skuteczność swoich landing page’y."]',
  '["Hundreds of customers use the feature, actively asking for insights and data to improve how their landing pages perform."]',
  '[{"label":"Frontend","items":["React","TypeScript"]},{"label":"Agent AI","items":["Mastra","Vercel AI SDK"]},{"label":"Automatyzacje","items":["n8n"]}]',
  '[{"label":"Frontend","items":["React","TypeScript"]},{"label":"AI agent","items":["Mastra","Vercel AI SDK"]},{"label":"Automation","items":["n8n"]}]',
  '[{"label":"Strona produktowa","url":"https://landingi.com/pl/produkt/solis/"},{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"Product page","url":"https://landingi.com/product/solis/"},{"label":"Repository","note":"closed source"}]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'i18n',
  4,
  true,
  'Internacjonalizacja aplikacji',
  'App internationalisation',
  'Landingi',
  'Landingi',
  'i18n od zera w istniejącej aplikacji i zautomatyzowany proces tłumaczeń z Lokalise — tłumacze pracują bez udziału dewelopera.',
  'i18n from scratch in an existing app and an automated translation workflow with Lokalise, so translators work without a developer.',
  '[{"value":"6","label":"wersji językowych"},{"value":"5 000+","label":"kluczy tłumaczeń"}]',
  '[{"value":"6","label":"languages"},{"value":"5,000+","label":"translation keys"}]',
  'Aplikacja Landingi obsługiwała jeden język, a każda zmiana tekstu wymagała udziału dewelopera — tłumacze nie mieli jak pracować samodzielnie.',
  'The Landingi app supported a single language, and every text change needed a developer, so translators had no way to work on their own.',
  'Wdrożenie i18n w istniejącej aplikacji od zera oraz zbudowanie procesu tłumaczeń wokół Lokalise, a na późniejszym etapie wsparcie przy wdrażaniu własnej aplikacji do zarządzania tłumaczeniami.',
  'Introducing i18n into an existing app from scratch and building the translation workflow around Lokalise, and later helping to roll out an in-house translation management app.',
  '["Warstwa i18n w aplikacji — wydzielenie tekstów z kodu do ponad 5 000 kluczy tłumaczeń.","Dwukierunkowa automatyzacja z Lokalise: wypychanie nowych kluczy z repozytorium i pobieranie gotowych tłumaczeń bez ręcznej pracy.","Własny skrypt wykrywający klucze nieużywane w kodzie — przy tej skali martwe pozycje realnie podbijały koszt subskrypcji Lokalise, więc ich usuwanie przełożyło się bezpośrednio na niższy rachunek.","Nadzór i wsparcie przy budowie własnej aplikacji do zarządzania tłumaczeniami."]',
  '["The app’s i18n layer: moving the texts out of the code into more than 5,000 translation keys.","Two-way automation with Lokalise: new keys are pushed from the repository and finished translations are pulled back with no manual work.","A custom script that finds keys no longer used in the code. At this scale dead keys noticeably raised the Lokalise subscription cost, so removing them directly lowered the bill.","Overseeing and supporting the build of an in-house translation management app."]',
  '[]',
  '[]',
  '["Tłumacze pracują samodzielnie w Lokalise, bez angażowania dewelopera do zmiany pojedynczego napisu.","Poprawka błędnego tłumaczenia trafia do aplikacji w minuty, zamiast czekać na cykl wydawniczy.","Deweloperzy przestali być wąskim gardłem w procesie tłumaczeń.","Kilkuset klientów korzysta z aplikacji w swoim języku.","Niższe wydatki na Lokalise — najpierw dzięki usunięciu martwych kluczy, potem dzięki własnej aplikacji do zarządzania tłumaczeniami."]',
  '["Translators work on their own in Lokalise, without needing a developer to change a single label.","A fix to a wrong translation reaches the app within minutes instead of waiting for the release cycle.","Developers are no longer a bottleneck in the translation process.","Hundreds of customers use the app in their own language.","Lower spending on Lokalise: first by removing dead keys, then thanks to the in-house translation management app."]',
  '[{"label":"Aplikacja","items":["i18next","react-i18next"]},{"label":"Proces tłumaczeń","items":["Lokalise API","GitHub Actions"]}]',
  '[{"label":"App","items":["i18next","react-i18next"]},{"label":"Translation workflow","items":["Lokalise API","GitHub Actions"]}]',
  '[{"label":"Aplikacja (po zalogowaniu)","url":"https://app.landingi.com"},{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"App (login required)","url":"https://app.landingi.com"},{"label":"Repository","note":"closed source"}]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'raportowanie-bledow',
  5,
  true,
  'Raportowanie błędów',
  'Error reporting',
  'Landingi',
  'Landingi',
  'Z nieużywanego Sentry do procesu, w którym raportowanie jest domyślne: pełny kontekst każdego błędu i odfiltrowany szum.',
  'From an unused Sentry to a process where reporting is the default: full context for every error and the noise filtered out.',
  '[]',
  '[]',
  'Sentry było w projekcie obecne, ale praktycznie nieużywane — błędy z frontendu nie trafiały do systemu, a o awariach na produkcji zespół dowiadywał się od klientów.',
  'Sentry was set up in the project but barely used: frontend errors weren’t reaching it, and the team learned about production failures from customers.',
  'Uporządkowanie obsługi błędów w całej aplikacji SPA i zbudowanie narzędzia, dzięki któremu raportowanie stało się domyślnym zachowaniem, a nie dodatkową pracą.',
  'Bringing order to error handling across the whole SPA and building a tool that made reporting the default behaviour rather than extra work.',
  '["Własna funkcja raportująca, upraszczająca logowanie błędów z frontendu. Podpięta przy każdym pobieraniu danych z backendu — wysyła kod błędu wraz z pełnym kontekstem potrzebnym do debugowania.","Wzbogacanie zdarzeń o kontekst: użytkownik, wersja aplikacji, release, breadcrumbs.","Filtrowanie szumu — wyciszenie błędów z rozszerzeń przeglądarki, botów i ResizeObservera, dzięki czemu w Sentry zostały wyłącznie zdarzenia, na które warto reagować.","Alerty i monitoring błędów w Sentry dla wielu projektów — kilkoma z nich zarządzam na bieżąco."]',
  '["A custom reporting function that makes logging frontend errors simple. It is hooked into every data fetch from the backend and sends the error code with the full context needed for debugging.","Enriching events with context: user, app version, release and breadcrumbs.","Filtering out noise: silencing errors from browser extensions, bots and ResizeObserver, so only events worth acting on reach Sentry.","Alerts and error monitoring in Sentry for many projects, several of which I manage day to day."]',
  '[]',
  '[]',
  '["Błędy produkcyjne wykrywane szybciej, w części przypadków zanim zgłosi je klient.","Krótszy czas debugowania — zgłoszenie zawiera od razu wszystko, co potrzebne, bez odtwarzania sytuacji u siebie.","Mniej zgłoszeń trafiających do supportu."]',
  '["Production errors are caught sooner, in some cases before a customer reports them.","Faster debugging: every report contains everything needed up front, with no need to reproduce the issue locally.","Fewer tickets reaching support."]',
  '[{"label":"Aplikacja","items":["Sentry","React","TypeScript"]}]',
  '[{"label":"App","items":["Sentry","React","TypeScript"]}]',
  '[{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"Repository","note":"closed source"}]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'analityka-mixpanel',
  6,
  true,
  'Standard analityki w Mixpanel',
  'Mixpanel analytics standard',
  'Landingi',
  'Landingi',
  'Z chaosu w nazwach zdarzeń do jednego standardu: tracking plan, wspólna funkcja wysyłki i uporządkowane dane, na których product managerowie pracują samodzielnie.',
  'From inconsistent event names to one standard: a tracking plan, a shared sending function and cleaned-up data that product managers work with on their own.',
  '[]',
  '[]',
  'Mixpanel był używany bez żadnej konwencji — każdy nazywał zdarzenia po swojemu, to samo działanie trafiało do systemu pod kilkoma nazwami, brakowało właściwości i dokumentacji. Danych nie dało się porównywać ani na nich polegać.',
  'Mixpanel was used without any convention: everyone named events their own way, the same action was tracked under several names, and properties and documentation were missing. The data couldn’t be compared or relied on.',
  'Opracowanie standardu śledzenia zdarzeń dla całej aplikacji i zbudowanie warstwy, która wymusza go w kodzie.',
  'Designing an event tracking standard for the whole app and building a layer that enforces it in code.',
  '["Tracking plan — konwencja nazewnictwa zdarzeń i ich właściwości, obowiązująca w całej aplikacji.","Wspólna funkcja wysyłająca zdarzenia, zbudowana analogicznie do warstwy raportowania błędów — jedno wejście zamiast rozproszonych wywołań SDK.","Uporządkowanie istniejących danych: usunięcie duplikatów i martwych zdarzeń narosłych przez lata.","Dokumentacja dla zespołu produktowego."]',
  '["A tracking plan: a naming convention for events and their properties that applies across the whole app.","A shared function for sending events, built the same way as the error reporting layer: one entry point instead of SDK calls scattered around the code.","Cleaning up the existing data: removing duplicates and dead events that had piled up over the years.","Documentation for the product team."]',
  '[]',
  '[]',
  '["Product managerowie pracują na danych samodzielnie, bez dopytywania dewelopera, czym różni się jedno podobnie brzmiące zdarzenie od drugiego.","Deweloperzy dodają nowe zdarzenia przez jedną funkcję, więc zgodność ze standardem jest domyślna, a nie zależna od czyjejś pamięci.","Dane z różnych obszarów aplikacji stały się porównywalne."]',
  '["Product managers work with the data on their own, without asking a developer how one similar-sounding event differs from another.","Developers add new events through a single function, so following the standard is the default rather than a matter of memory.","Data from different areas of the app became comparable."]',
  '[{"label":"Aplikacja","items":["Mixpanel","React","TypeScript"]}]',
  '[{"label":"App","items":["Mixpanel","React","TypeScript"]}]',
  '[{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"Repository","note":"closed source"}]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'automatyzacje-ai',
  3,
  true,
  'Automatyzacje AI w zespole',
  'AI automation for the team',
  'Landingi',
  'Landingi',
  'Skille AI dla zespołu: taski w Jirze tworzone z dokumentacji biznesowej, drafty PR-ów, wsparcie code review i ustrukturyzowane planowanie funkcjonalności.',
  'AI skills for the team: Jira tasks created from business documentation, PR drafts, code review support and structured feature planning.',
  '[]',
  '[]',
  'Powtarzalne czynności wokół kodu — zakładanie tasków, tworzenie i opisywanie pull requestów, code review, prowadzenie nowych funkcjonalności od planu do wdrożenia — pochłaniały czas zespołu i były wykonywane różnie przez różne osoby.',
  'Repetitive work around the code (creating tasks, opening and describing pull requests, code review, taking new features from plan to release) took up the team’s time and was done differently by different people.',
  'Tworzenie i wdrażanie skilli AI oraz automatyzacji dla zespołu deweloperskiego, standaryzujących te czynności i skracających czas potrzebny na ich wykonanie.',
  'Creating and rolling out AI skills and automations for the development team that standardise this work and cut the time it takes.',
  '["Automatyczne tworzenie tasków w Jirze na podstawie dokumentacji biznesowej.","Tworzenie pull requestów wraz z opisem zgodnym z firmową konwencją.","Wsparcie code review: baza wiedzy o projekcie, na której opiera się agent, oraz dedykowane skille do przeglądu kodu.","AI SDLC — cały cykl wytwarzania funkcjonalności wspierany przez AI, od planowania po implementację, w oparciu o proces AI Hero Matta Pococka (aihero.dev), dostosowany do sposobu pracy zespołu.","Serwery MCP wykorzystane w wielu miejscach procesu, dzięki którym agenci pracują bezpośrednio na narzędziach zespołu."]',
  '["Automated creation of Jira tasks from business documentation.","Opening pull requests together with a description that follows the company’s convention.","Code review support: a project knowledge base the agent relies on, plus dedicated code review skills.","AI SDLC: the whole feature lifecycle supported by AI, from planning to implementation, based on Matt Pocock’s AI Hero process (aihero.dev) and adapted to the way the team works.","MCP servers used in many parts of the process, so the agents work directly with the team’s tools."]',
  '[]',
  '[]',
  '["Powtarzalne czynności wokół kodu wykonywane szybciej i w jednym, spójnym standardzie niezależnie od osoby.","Ujednolicony, wspierany przez AI proces prowadzenia funkcjonalności — od planu po implementację.","Narzędzia używane przez cały zespół, nie tylko przeze mnie."]',
  '["Repetitive work around the code gets done faster and to one consistent standard, whoever does it.","One shared, AI-supported process for taking features from plan to implementation.","Tools used by the whole team, not just by me."]',
  '[{"label":"Narzędzia","items":["Codex","Claude Code","MCP","AGENTS.md","GitHub","Jira"]}]',
  '[{"label":"Tools","items":["Codex","Claude Code","MCP","AGENTS.md","GitHub","Jira"]}]',
  '[]',
  '[]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'czat-wsparcia-ai',
  7,
  true,
  'Czat wsparcia AI',
  'AI support chat',
  'Landingi',
  'Landingi',
  'Czat AI wbudowany we wszystkie aplikacje Landingi. Odpowiada na powtarzalne pytania na podstawie bazy wiedzy, a trudniejsze rozmowy przekazuje do człowieka.',
  'An AI chat built into every Landingi app. It answers repetitive questions from the knowledge base and hands harder conversations over to a person.',
  '[{"value":"24/7","label":"wsparcia klientów"}]',
  '[{"value":"24/7","label":"customer support"}]',
  'Do ludzkiego supportu trafiała bardzo duża liczba zgłoszeń, a znaczna część z nich dotyczyła wciąż tych samych pytań. Zespół wsparcia był przeciążony sprawami, które dało się obsłużyć automatycznie.',
  'A very large number of tickets reached the human support team, and many of them were the same questions over and over. The support team was overloaded with cases that could be handled automatically.',
  'Byłem częścią zespołu, który zaprojektował i wdrożył czat. Odpowiadałem za cały frontend i integrację czatu z n8n w React, za architekturę rozwiązania po stronie frontu i backendu oraz za usprawnianie bazy wiedzy, z której korzysta czat.',
  'I was part of the team that designed and built the chat. I was responsible for the whole frontend and the chat’s integration with n8n in React, for the solution’s architecture on both the frontend and the backend, and for improving the knowledge base the chat draws on.',
  '["Interfejs czatu w React zintegrowany z przepływami n8n, dostępny we wszystkich aplikacjach Landingi.","Architektura po stronie frontu i backendu: zapisywanie historii rozmów oraz możliwość rozpoczęcia nowego czatu bez kontekstu poprzedniej rozmowy.","Baza wiedzy czatu oparta na dokumentacji, centrum pomocy, artykułach i historii zgłoszeń, rozwijana tak, żeby odpowiedzi były coraz trafniejsze.","Przekazanie rozmowy do człowieka, gdy użytkownik o to poprosi albo gdy czat rozpozna, że jest zdenerwowany."]',
  '["A chat interface in React integrated with n8n workflows, available in every Landingi app.","Frontend and backend architecture: saving conversation history and letting users start a new chat without the context of the previous one.","A knowledge base for the chat built from documentation, the help centre, articles and ticket history, developed so that answers keep getting more accurate.","Handing the conversation over to a person when the user asks for it or when the chat recognises that they are frustrated."]',
  '[{"title":"Odpowiedzi oparte na wiedzy, nie na zgadywaniu","body":"Jakość odpowiedzi zależała przede wszystkim od bazy wiedzy. Tam, gdzie czat się mylił albo odpowiadał zbyt ogólnie, porządkowaliśmy i uzupełnialiśmy jej treści."},{"title":"Kontekst rozmowy","body":"Historia musi zostać zachowana, ale stary kontekst nie może psuć odpowiedzi na nowy problem. Stąd zapisywanie historii po stronie backendu i osobna możliwość rozpoczęcia czystej rozmowy."},{"title":"Moment przekazania do człowieka","body":"Czat nie może zatrzymywać kogoś, kto potrzebuje pomocy człowieka. Rozmowa trafia do supportu, gdy użytkownik o to poprosi albo gdy jego wiadomości wskazują na frustrację."}]',
  '[{"title":"Answers based on knowledge, not guesswork","body":"Answer quality depended above all on the knowledge base. Where the chat got things wrong or answered too vaguely, we cleaned up and filled in its content."},{"title":"Conversation context","body":"History has to be kept, but old context must not spoil the answer to a new problem. Hence history saved on the backend and a separate option to start a clean conversation."},{"title":"When to hand over to a person","body":"The chat must not hold back someone who needs a human. The conversation goes to support when the user asks for it or when their messages show frustration."}]',
  '["Mniej zgłoszeń trafiających do ludzkiego supportu.","Szybsze odpowiedzi na powtarzające się pytania.","Wsparcie dostępne 24 godziny na dobę, także poza godzinami pracy zespołu.","Czat dostępny we wszystkich aplikacjach Landingi i używany przez wielu użytkowników."]',
  '["Fewer tickets reaching the human support team.","Faster answers to recurring questions.","Support available 24 hours a day, including outside the team’s working hours.","The chat is available in every Landingi app and used by many users."]',
  '[{"label":"Czat","items":["React","TypeScript","JavaScript"]},{"label":"Automatyzacje i AI","items":["n8n"]}]',
  '[{"label":"Chat","items":["React","TypeScript","JavaScript"]},{"label":"Automation and AI","items":["n8n"]}]',
  '[{"label":"Aplikacja (po zalogowaniu)","url":"https://app.landingi.com"},{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"App (login required)","url":"https://app.landingi.com"},{"label":"Repository","note":"closed source"}]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'rejestracja-i-logowanie',
  8,
  true,
  'Rejestracja i logowanie',
  'Registration and sign-in',
  'Landingi',
  'Landingi',
  'Ujednolicone wejście do platformy: rejestracja, logowanie, weryfikacja e-maila, odzyskiwanie hasła i 2FA w jednym spójnym przepływie zamiast kilku rozproszonych wariantów.',
  'A unified way into the platform: registration, sign-in, email verification, password recovery and 2FA in one consistent flow instead of several scattered variants.',
  '[]',
  '[]',
  'Wejście do platformy było rozbite na kilka wariantów rejestracji i luźno powiązane ekrany logowania, weryfikacji i odzyskiwania dostępu. Taki obszar trudno było utrzymywać i rozwijać, a użytkownik w każdym miejscu trafiał na trochę inne zachowanie.',
  'Getting into the platform was split across several registration variants and loosely connected screens for sign-in, verification and account recovery. The area was hard to maintain and extend, and users met slightly different behaviour at every step.',
  'Implementacja całego frontendu nowego przepływu na podstawie projektu, łącznie z jego architekturą.',
  'Implementing the whole frontend of the new flow from the design, including its architecture.',
  '["Ekrany rejestracji, logowania, resetu i zmiany hasła, weryfikacji e-maila, 2FA i odzyskiwania konta kluczem.","Logowanie i rejestracja przez Google i Microsoft.","Wspólne komponenty formularzy z jedną logiką walidacji, komunikatami błędów i stanami: ładowanie, zablokowany, sukces, błąd.","Weryfikacja e-maila kodem, z możliwością ponownego wysłania.","Krok płatności przy rozpoczęciu triala.","Układy jedno- i dwukolumnowe, responsywność oraz tryb jasny i ciemny."]',
  '["Screens for registration, sign-in, password reset and change, email verification, 2FA and account recovery with a recovery key.","Sign-in and registration with Google and Microsoft.","Shared form components with one validation logic, error messages and states: loading, disabled, success and failure.","Email verification with a code that can be sent again.","A payment step when starting a trial.","One- and two-column layouts, responsive behaviour and light and dark mode."]',
  '[{"title":"Walidacja","body":"Wiele formularzy z różnymi regułami, a zachowanie ma być wszędzie takie samo. Reguły opisane w Zod i podpięte przez React Hook Form dały jeden sposób walidacji i komunikowania błędów. Wymagania, np. co do hasła, użytkownik widzi przed wysłaniem formularza, a nie dopiero po błędzie."},{"title":"Krytyczne miejsce bez marginesu na błąd","body":"Przez rejestrację i logowanie przechodzi każdy użytkownik, więc każdy błąd oznacza utraconego klienta albo zablokowany dostęp do konta. Stany i przypadki brzegowe pokryłem testami w Vitest i uzgodniłem z QA przed wdrożeniem."}]',
  '[{"title":"Validation","body":"Many forms with different rules, yet the behaviour has to be the same everywhere. Rules described in Zod and wired up with React Hook Form gave one way to validate and to communicate errors. Users see requirements, such as the password rules, before they submit the form rather than only after an error."},{"title":"A critical spot with no room for error","body":"Every user goes through registration and sign-in, so any bug means a lost customer or a locked account. I covered the states and edge cases with Vitest tests and agreed them with QA before release."}]',
  '["Jeden spójny przepływ wejścia do platformy zamiast kilku wariantów.","Prostszy w utrzymaniu i rozwijaniu kod ekranów uwierzytelniania.","Przepływ przygotowany pod przyszłe zmiany w onboardingu, cenniku i zakładaniu konta."]',
  '["One consistent way into the platform instead of several variants.","Authentication screens whose code is simpler to maintain and extend.","A flow ready for future changes to onboarding, pricing and account setup."]',
  '[{"label":"Aplikacja","items":["React","TypeScript","SWR"]},{"label":"Formularze","items":["React Hook Form","Zod"]},{"label":"Testy","items":["Vitest"]}]',
  '[{"label":"App","items":["React","TypeScript","SWR"]},{"label":"Forms","items":["React Hook Form","Zod"]},{"label":"Testing","items":["Vitest"]}]',
  '[{"label":"Rejestracja","url":"https://app.landingi.com/register"},{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"Registration","url":"https://app.landingi.com/register"},{"label":"Repository","note":"closed source"}]'
);

insert into public.projects (
  slug,
  sort_order,
  published,
  title_pl,
  title_en,
  context_pl,
  context_en,
  summary_pl,
  summary_en,
  metrics_pl,
  metrics_en,
  problem_pl,
  problem_en,
  role_pl,
  role_en,
  built_pl,
  built_en,
  challenges_pl,
  challenges_en,
  outcomes_pl,
  outcomes_en,
  stack_pl,
  stack_en,
  links_pl,
  links_en
) values (
  'mapy-klikniec-i-scrolla',
  9,
  true,
  'Mapy kliknięć i scrolla',
  'Event and scroll maps',
  'Landingi',
  'Landingi',
  'Heatmapy kliknięć i mapy scrolla nałożone na opublikowany landing page, zbudowane na danych z EventTrackera. Klient widzi, gdzie użytkownicy klikają i jak daleko przewijają stronę.',
  'Click heatmaps and scroll maps laid over a published landing page, built on EventTracker data. Customers see where visitors click and how far they scroll.',
  '[]',
  '[]',
  'EventTracker zbierał dane o zachowaniu odwiedzających, ale tabele i wykresy nie pokazują, gdzie na stronie to się dzieje. Klienci potrzebowali zobaczyć dane bezpośrednio na swoim landing page’u: które elementy przyciągają uwagę, a do którego miejsca odwiedzający w ogóle docierają.',
  'EventTracker collected data on visitor behaviour, but tables and charts don’t show where on the page it happens. Customers needed to see the data right on their landing page: which elements draw attention and how far down visitors actually get.',
  'Implementacja całego frontendu map, łącznie z jego architekturą: renderowanie podglądu strony z nałożonymi danymi, warstwy heatmapy i scrolla oraz interakcje z elementami.',
  'Implementing the whole frontend of the maps, including its architecture: rendering the page preview with the data on top, the heatmap and scroll layers, and the interactions with elements.',
  '["Mapa zdarzeń: heatmapa kliknięć nałożona na podgląd strony, ze skalą od najczęściej do najrzadziej klikanych miejsc.","Szczegóły elementu po kliknięciu: nazwa zdarzenia, liczba zdarzeń i wizyt oraz ich udział we wszystkich.","Mapa scrolla: pasma pokazujące, jaki procent odwiedzających dotarł do danej głębokości strony.","Przełączanie widoku między desktopem, tabletem i telefonem oraz wybór zakresu dat.","Osobne dane dla każdego wariantu strony w testach A/B."]',
  '["An event map: a click heatmap laid over the page preview, with a scale from the most to the least clicked spots.","Element details on click: the event name, the number of events and visits, and their share of the total.","A scroll map: bands showing what percentage of visitors reached each depth of the page.","Switching the view between desktop, tablet and phone, and choosing the date range.","Separate data for each page variant in A/B tests."]',
  '[{"title":"Dane w dokładnie tym miejscu","body":"Zdarzenia muszą trafić na właściwe elementy strony, choć układ zmienia się z rozdzielczością. Stąd osobne widoki dla desktopu, tabletu i telefonu oraz przypisanie zdarzeń do identyfikatorów elementów, a nie do współrzędnych."},{"title":"Bezpieczny podgląd strony","body":"Strona klienta jest renderowana jako podgląd bez uruchamiania jego skryptów i widżetów HTML. Dzięki temu mapa nie zależy od cudzego kodu, a użytkownik wie, czego podgląd nie pokaże."},{"title":"Czytelność przy dużej liczbie danych","body":"Heatmapa i pasma scrolla muszą pozostać płynne i czytelne zarówno przy kilkudziesięciu, jak i przy tysiącach wizyt."}]',
  '[{"title":"Data in exactly the right place","body":"Events have to land on the right elements of the page, even though the layout changes with the screen size. Hence separate views for desktop, tablet and phone, and events tied to element IDs rather than to coordinates."},{"title":"A safe page preview","body":"The customer’s page is rendered as a preview without running their scripts and HTML widgets. That way the map doesn’t depend on someone else’s code, and users know what the preview won’t show."},{"title":"Readable with a lot of data","body":"The heatmap and the scroll bands have to stay smooth and readable with a few dozen visits as well as with thousands."}]',
  '["Klienci widzą zachowanie odwiedzających bezpośrednio na swojej stronie, bez zewnętrznych narzędzi typu Hotjar.","Łatwiej znaleźć elementy, które nie działają, np. CTA, którego nikt nie klika, albo sekcję, do której mało kto dociera.","Kolejna funkcjonalność zbudowana na danych z EventTrackera."]',
  '["Customers see visitor behaviour right on their own page, without external tools such as Hotjar.","It’s easier to spot what isn’t working, such as a CTA nobody clicks or a section few visitors reach.","Another feature built on EventTracker data."]',
  '[{"label":"Aplikacja","items":["React","TypeScript","SWR"]}]',
  '[{"label":"App","items":["React","TypeScript","SWR"]}]',
  '[{"label":"Aplikacja (po zalogowaniu)","url":"https://app.landingi.com"},{"label":"Repozytorium","note":"kod zamknięty"}]',
  '[{"label":"App (login required)","url":"https://app.landingi.com"},{"label":"Repository","note":"closed source"}]'
);

insert into public.project_skills (project_id, skill_id)
select project.id, skill.id
from (values
  ('eventtracker', 'React'),
  ('eventtracker', 'TypeScript'),
  ('eventtracker', 'SWR'),
  ('eventtracker', 'Recharts'),
  ('eventtracker', 'Vite'),
  ('eventtracker', 'GitHub Actions'),
  ('solis', 'React'),
  ('solis', 'TypeScript'),
  ('solis', 'Mastra'),
  ('solis', 'Vercel AI SDK'),
  ('solis', 'n8n'),
  ('i18n', 'React'),
  ('i18n', 'i18next'),
  ('i18n', 'Lokalise'),
  ('i18n', 'GitHub Actions'),
  ('raportowanie-bledow', 'Sentry'),
  ('raportowanie-bledow', 'React'),
  ('raportowanie-bledow', 'TypeScript'),
  ('analityka-mixpanel', 'Mixpanel'),
  ('analityka-mixpanel', 'React'),
  ('analityka-mixpanel', 'TypeScript'),
  ('automatyzacje-ai', 'Codex'),
  ('automatyzacje-ai', 'Claude Code'),
  ('automatyzacje-ai', 'MCP'),
  ('automatyzacje-ai', 'GitHub'),
  ('automatyzacje-ai', 'Jira'),
  ('czat-wsparcia-ai', 'React'),
  ('czat-wsparcia-ai', 'TypeScript'),
  ('czat-wsparcia-ai', 'JavaScript'),
  ('czat-wsparcia-ai', 'n8n'),
  ('rejestracja-i-logowanie', 'React'),
  ('rejestracja-i-logowanie', 'TypeScript'),
  ('rejestracja-i-logowanie', 'SWR'),
  ('rejestracja-i-logowanie', 'React Hook Form'),
  ('rejestracja-i-logowanie', 'Zod'),
  ('rejestracja-i-logowanie', 'Vitest'),
  ('mapy-klikniec-i-scrolla', 'React'),
  ('mapy-klikniec-i-scrolla', 'TypeScript'),
  ('mapy-klikniec-i-scrolla', 'SWR')
) as link (slug, skill)
join public.projects as project on project.slug = link.slug
join public.skills as skill on skill.name = link.skill;
