create table public.skill_categories (
  id integer generated by default as identity primary key,
  name_pl text not null,
  name_en text not null,
  sort_order integer not null default 0
);

alter table public.skill_categories enable row level security;

grant select on public.skill_categories to anon;

create policy "Skill categories are readable"
  on public.skill_categories
  for select
  to anon
  using (true);

create table public.skills (
  id integer generated by default as identity primary key,
  name text not null unique,
  category_id integer not null references public.skill_categories (id) on delete restrict,
  sort_order integer not null default 0
);

create index skills_category_id_idx on public.skills (category_id);

alter table public.skills enable row level security;

grant select on public.skills to anon;

create policy "Skills are readable"
  on public.skills
  for select
  to anon
  using (true);

create table public.projects (
  id integer generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  sort_order integer not null default 0,
  published boolean not null default true,

  title_pl text not null check (btrim(title_pl) <> ''),
  title_en text not null check (btrim(title_en) <> ''),
  context_pl text not null check (btrim(context_pl) <> ''),
  context_en text not null check (btrim(context_en) <> ''),
  summary_pl text not null check (btrim(summary_pl) <> ''),
  summary_en text not null check (btrim(summary_en) <> ''),
  problem_pl text not null default '',
  problem_en text not null default '',
  role_pl text not null default '',
  role_en text not null default '',

  metrics_pl jsonb not null default '[]' check (jsonb_typeof(metrics_pl) = 'array'),
  metrics_en jsonb not null default '[]' check (jsonb_typeof(metrics_en) = 'array'),
  built_pl jsonb not null default '[]' check (jsonb_typeof(built_pl) = 'array'),
  built_en jsonb not null default '[]' check (jsonb_typeof(built_en) = 'array'),
  challenges_pl jsonb not null default '[]' check (jsonb_typeof(challenges_pl) = 'array'),
  challenges_en jsonb not null default '[]' check (jsonb_typeof(challenges_en) = 'array'),
  outcomes_pl jsonb not null default '[]' check (jsonb_typeof(outcomes_pl) = 'array'),
  outcomes_en jsonb not null default '[]' check (jsonb_typeof(outcomes_en) = 'array'),
  stack_pl jsonb not null default '[]' check (jsonb_typeof(stack_pl) = 'array'),
  stack_en jsonb not null default '[]' check (jsonb_typeof(stack_en) = 'array'),
  links_pl jsonb not null default '[]' check (jsonb_typeof(links_pl) = 'array'),
  links_en jsonb not null default '[]' check (jsonb_typeof(links_en) = 'array')
);

alter table public.projects enable row level security;

grant select on public.projects to anon;

create policy "Published Projects are readable"
  on public.projects
  for select
  to anon
  using (published);

create table public.project_skills (
  project_id integer not null references public.projects (id) on delete cascade,
  skill_id integer not null references public.skills (id) on delete cascade,
  primary key (project_id, skill_id)
);

create index project_skills_skill_id_idx on public.project_skills (skill_id);

create table public.project_screenshots (
  id integer generated by default as identity primary key,
  project_id integer not null references public.projects (id) on delete cascade,
  storage_path text not null check (btrim(storage_path) <> ''),
  alt_pl text not null check (btrim(alt_pl) <> ''),
  alt_en text not null check (btrim(alt_en) <> ''),
  sort_order integer not null default 0
);

create index project_screenshots_project_id_idx on public.project_screenshots (project_id);

alter table public.project_skills enable row level security;
alter table public.project_screenshots enable row level security;

grant select on public.project_skills, public.project_screenshots to anon;

create policy "Skills of published Projects are readable"
  on public.project_skills
  for select
  to anon
  using (exists (
    select 1 from public.projects
    where projects.id = project_skills.project_id and projects.published
  ));

create policy "Screenshots of published Projects are readable"
  on public.project_screenshots
  for select
  to anon
  using (exists (
    select 1 from public.projects
    where projects.id = project_screenshots.project_id and projects.published
  ));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'screenshots',
  'screenshots',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp', 'image/avif']
);

-- Contact messages are written server-side with the secret key only: no grant and no policy for anon.
create table public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  locale text not null check (locale in ('pl', 'en')),
  ip_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

grant select, insert on public.contact_messages to service_role;
